/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCommunitiesRouteImport } from './routes/app/communities'
import { Route as AppEventsRouteImport } from './routes/app/events'
import { Route as AppInviteRouteImport } from './routes/app/invite'
import { Route as AppNeedsRouteImport } from './routes/app/needs'
import { Route as AppNeighborsRouteImport } from './routes/app/neighbors'
import { Route as AppPlacesRouteImport } from './routes/app/places'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppNeedsRoute = AppNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AppRoute,
} as any)
const AppNeighborsRoute = AppNeighborsRouteImport.update({
  id: '/neighbors',
  path: '/neighbors',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/communities': typeof AppCommunitiesRoute
  '/app/events': typeof AppEventsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/needs': typeof AppNeedsRoute
  '/app/neighbors': typeof AppNeighborsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$code': typeof JoinCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/communities': typeof AppCommunitiesRoute
  '/app/events': typeof AppEventsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/needs': typeof AppNeedsRoute
  '/app/neighbors': typeof AppNeighborsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$code': typeof JoinCodeRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/communities': typeof AppCommunitiesRoute
  '/app/events': typeof AppEventsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/needs': typeof AppNeedsRoute
  '/app/neighbors': typeof AppNeighborsRoute
  '/app/places': typeof AppPlacesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$code': typeof JoinCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/communities'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/communities'
    | '/app/events'
    | '/app/invite'
    | '/app/needs'
    | '/app/neighbors'
    | '/app/places'
    | '/app/services'
    | '/app/settings'
    | '/c/$slug'
    | '/join/$code'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communities'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/communities'
    | '/app/events'
    | '/app/invite'
    | '/app/needs'
    | '/app/neighbors'
    | '/app/places'
    | '/app/services'
    | '/app/settings'
    | '/c/$slug'
    | '/join/$code'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/communities'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/communities'
    | '/app/events'
    | '/app/invite'
    | '/app/needs'
    | '/app/neighbors'
    | '/app/places'
    | '/app/services'
    | '/app/settings'
    | '/c/$slug'
    | '/join/$code'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  CSlugRoute: typeof CSlugRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communities': {
      id: '/app/communities'
      path: '/communities'
      fullPath: '/app/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invite': {
      id: '/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/needs': {
      id: '/app/needs'
      path: '/needs'
      fullPath: '/app/needs'
      preLoaderRoute: typeof AppNeedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/neighbors': {
      id: '/app/neighbors'
      path: '/neighbors'
      fullPath: '/app/neighbors'
      preLoaderRoute: typeof AppNeighborsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/places': {
      id: '/app/places'
      path: '/places'
      fullPath: '/app/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCommunitiesRoute: typeof AppCommunitiesRoute
  AppEventsRoute: typeof AppEventsRoute
  AppInviteRoute: typeof AppInviteRoute
  AppNeedsRoute: typeof AppNeedsRoute
  AppNeighborsRoute: typeof AppNeighborsRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunitiesRoute: AppCommunitiesRoute,
  AppEventsRoute: AppEventsRoute,
  AppInviteRoute: AppInviteRoute,
  AppNeedsRoute: AppNeedsRoute,
  AppNeighborsRoute: AppNeighborsRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CommunitiesRoute: CommunitiesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  CSlugRoute: CSlugRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
